language: node_js
node_js:
- '8'
branches:
  only:
  - "/^v[0-9]/"
services:
- redis
- mongodb
before_deploy:
- npm run build
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  api_key:
    secure: XmrfhODbEycUQ05QlsuGedpO8nc2vLZaoOjdrUGP8AZulv/f2maC2JTF3JoVSfzm6PJjToMXMav2UXLZpoOM11cHrfCrUyVIxD1rgxbFohDdMoxJUcLVcA+iaPQubexodluwcc5Na8cPDisq8QplgTmFN+EJLHgFPvZCXeKYWNw=
  on:
    tags: true
    branches: true
